name: Jibril Loud Runtime (oss soup)

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Jibril (must succeed)
        uses: garnet-org/action@v1
        with:
          api_token: ${{ secrets.GARNET_API_TOKEN }}
          api_url: https://jibril.garnet.ai
          debug: true
          continue_on_error: false
          jibril_version: latest
          garnetctl_version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run run
